version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/deploy/app"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/deploy/geo"
    schedule:
      interval: "daily"
