port 6380
bind 0.0.0.0
protected-mode yes

tcp-backlog 2048
maxclients 10000
tcp-keepalive 300

maxmemory 24mb
maxmemory-policy allkeys-lfu

save ""
appendonly no

loglevel notice

slowlog-log-slower-than 3000
slowlog-max-len 128

protected-mode yes
