port 6379
bind 0.0.0.0

tcp-backlog 511
maxclients 10000
tcp-keepalive 300

maxmemory 1gb
maxmemory-policy allkeys-lru

save ""
appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 50
auto-aof-rewrite-min-size 128mb

maxclients 10000
slowlog-log-slower-than 10000
slowlog-max-len 128

protected-mode no
