tcp_nodelay on;
tcp_nopush on;

sendfile on;
sendfile_max_chunk 512k;

keepalive_timeout 75s;
keepalive_requests 100000;

reset_timedout_connection on;

client_body_timeout 10s;
send_timeout 5s;
client_header_timeout 10s;

proxy_socket_keepalive on;
