geo $is_exempt {
    default 0;
    127.0.0.1 1;
    172.19.0.0/24 1;
    172.18.0.0/24 1;
}

map $is_exempt $limit_key {
    0 $binary_remote_addr;
    1 "";  # no limits
}

limit_req_zone $limit_key zone=api_flood_shield:50m rate=30r/s;
limit_req_zone $limit_key zone=ws_storm_shield:50m  rate=3r/s;
limit_conn_zone $limit_key zone=ws_conn_limit:50m;

limit_req_status  429;
limit_conn_status 429;
limit_req_log_level warn;
