server_tokens off;
proxy_hide_header X-Powered-By;
proxy_hide_header X-AspNet-Version;

add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header X-XSS-Protection "0" always;
add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=()" always;

add_header Content-Security-Policy "\
    default-src 'self'; \
    connect-src 'self' https://example.com wss://example.com; \
    script-src 'self'; \
    style-src 'self' 'unsafe-inline'; \
    img-src 'self' data: blob: https://amazonaws.com; \
    font-src 'self' data:; \
    frame-ancestors 'none'; \
    object-src 'none'; \
    base-uri 'self'; \
    form-action 'self'; \
    upgrade-insecure-requests; \
" always;

location ~ /\.(?!well-known) {
    deny all;
    access_log off;
    log_not_found off;
}

location ~* \.(conf|config|sql|log|sh|inc|swp|dist|bak|env|yaml|yml)$ {
    deny all;
    access_log off;
    log_not_found off;
}
