"""initial revision

Revision ID: 4e9897b69762
Revises:
Create Date: 2026-05-17 20:18:42.532972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9897b69762'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('email_verification_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_table('profiles',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('display_name', sa.String(length=255), nullable=False),
            sa.Column('username', sa.String(length=50), nullable=False),
            sa.Column('bio', sa.String(length=500), nullable=True),
            sa.Column('avatar_path', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id')
    )
    op.create_index('uq_profiles_username', 'profiles', ['username'], unique=True)
    op.create_table('subscriptions',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('subscriber_id', sa.Uuid(), nullable=False),
            sa.Column('author_id', sa.Uuid(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('subscriber_id', 'author_id', name='uq_subscriber_author')
    )
    op.create_index('idx_subs_author_id', 'subscriptions', ['author_id'], unique=False)
    op.create_index('idx_subs_subscriber_id', 'subscriptions', ['subscriber_id'], unique=False)
    op.create_table('user_identities',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('provider', sa.String(length=255), nullable=False),
            sa.Column('provider_user_id', sa.String(length=255), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index('idx_identities_user_id', 'user_identities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_identities_user_id', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('idx_subs_subscriber_id', table_name='subscriptions')
    op.drop_index('idx_subs_author_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('uq_profiles_username', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('uq_active_users_email', table_name='users', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('users')
    # ### end Alembic commands ###
