"""initial

Revision ID: 2013c44ed2f6
Revises:
Create Date: 2026-06-27 20:40:22.365753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2013c44ed2f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'BANNED', name='userstatus'), nullable=False),
            sa.Column('email_verification_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('nickname', sa.String(length=50), nullable=False),
            sa.Column('username', sa.String(length=20), nullable=False),
            sa.Column('bio', sa.String(length=500), nullable=True),
            sa.Column('fid', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('uq_profiles_username_lowercase', 'profiles', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('user_identities',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=False),
            sa.Column('provider', sa.String(length=255), nullable=False),
            sa.Column('provider_user_id', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index('idx_identities_user_id', 'user_identities', ['user_id'], unique=False)
    op.execute("ALTER TABLE profiles SET (fillfactor = 85);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_identities_user_id', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('uq_profiles_username_lowercase', table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
