resolver 127.0.0.11 valid=10s;

location ~* ^/media/(?<volume_id>.+)$ {
    limit_req zone=photo_shield burst=30 nodelay;

    set $seaweed_upstream "sw_volume_1:8080";

    rewrite ^/media/(.*)$ /$1 break;
    proxy_pass http://$seaweed_upstream;

    add_header Cache-Control "no-cache, must-revalidate" always;
    proxy_pass_header ETag;

    proxy_buffering          on;
    proxy_buffer_size        128k;
    proxy_buffers            32 128k;
    proxy_max_temp_file_size 5m;

    proxy_request_buffering  off;

    proxy_read_timeout 15s;
    proxy_send_timeout 15s;
}
