proxy_intercept_errors on;

error_page 400 403 404 405 413 500 502 503 504 /error.html;

location = /error.html {
    root /etc/angie;
    internal;
    add_header Content-Type text/html;
    access_log off;
}
